namespace MivtzarNaki.Core;

/// <summary>Runtime identity generated by MSBuild from Directory.Build.props.</summary>
public static class AppIdentity
{
    public static Version Version { get; } = ReadVersion();
    public static string DisplayVersion => Version.ToString();

    private static Version ReadVersion()
    {
        var version = typeof(AppIdentity).Assembly.GetName().Version
            ?? throw new InvalidOperationException("Application assembly has no version.");
        return new Version(version.Major, version.Minor, version.Build);
    }
}
